# Generated by Django 4.2.1 on 2023-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
