# Generated by Django 4.2.1 on 2023-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='collected',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
